name: surpraise_backend_dependencies
description: A project that exports packages needed on surpraise backend project
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  faker: ^2.0.0
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.16.0
dependencies:
  equatable: ^2.0.5
  ez_either: ^1.0.0
  mongo_dart: ^0.8.0
  string_validator: ^0.3.0
